### ISSUE TITLE
Interface Fill Station Pi with sensors and actuators

### ISSUE THREAD

**Issue by ZachGarcia42** [cornellrocketryteam/Ground-Software#11]
As sensors and actuators are finalized, we should interface with them from the Fill Station Pi. This should mostly follow the structure of  Pull Request #1 (Add temporary ducer implementation)
```[tasklist]
### Tasks
- [x] Interface code with QD stepper motor driver
- [ ] Interface code with Ignitors
- [x] Interface with Ball Valve Board
- [ ] Interface code with Load Cell
- [ ] Interface code with AV Bay Umbilical (Format not yet determined)
- [ ] Interface with Igniter continuity sensors
- [x] Separate GRPC client and server side (fill station should be server)
- [x] Create protobuffs (commands and responses) for our telemetry
- [x] Integrate our GRPC with the ground station via the WiFi bridge
```
